RunGroopWebApp/RunGroopWebApp/Controllers/ClubController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroopWebApp.Data;
using RunGroopWebApp.Models;
using RunGroopWebApp.Models.ViewModels;

namespace RunGroopWebApp.Controllers
{
    [Authorize]
    public class ClubController : Controller
    {
        private AppDbContext _context { get; }
        private readonly UserManager<AppUser> _userManager;

        public ClubController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var clubs = _context.Clubs.Include(c => c.Address).ToList();
            return View(clubs);
        }

        public IActionResult Detail(int id)
        {
            var club = _context.Clubs.Include(c => c.Address).FirstOrDefault(x => x.Id == id);

            return View(club);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Club club)
        {
            if (!ModelState.IsValid)
            {
                return View(club);
            }

            var currentUserId = _userManager.GetUserId(User);
            club.AppUserId = currentUserId;

            _context.Clubs.Add(club);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var club = _context.Clubs.Where(c => c.Id == id).FirstOrDefault();
            if (club == null) return View("Error");
            var clubVM = new EditClubViewModel
            {
                Title = club.Title,
                Description = club.Description,
                AddressId = club.AddressId,
                Address = club.Address,
                Url = club.Image,
                Category = club.ClubCategory
            };
            return View(clubVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditClubViewModel clubvm)
        {


            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Falha ao editar clube");
                return View("Edit", clubvm);
            }

            var club = new Club
            {
                Id = id,
                Title = clubvm.Title,
                Description = clubvm.Description,
                AddressId = clubvm.AddressId,
                Address = clubvm.Address,
            };

            _context.Clubs.Update(club);

            await _context.SaveChangesAsync();


            return RedirectToAction("Index");
        }
    }
}

RunGroopWebApp/RunGroopWebApp/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroopWebApp.Data;
using RunGroopWebApp.Models;
using RunGroopWebApp.Models.ViewModels;

namespace RunGroopWebApp.Controllers
{
    public class DashboardController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        // should have built a complete user service in order to not mix responsabilities around app
        public DashboardController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {

            var currentUserId = _userManager.GetUserId(User);
            var usersClubs = await _context.Clubs.Where(c => c.AppUserId == currentUserId).ToListAsync();
            var usersRaces = await _context.Races.Where(c => c.AppUserId == currentUserId).ToListAsync();


            var dashVm = new DashboardViewModel
            {
                Clubs = usersClubs,
                Races = usersRaces,
            };

            return View(dashVm);
        }
    }
}

RunGroopWebApp/RunGroopWebApp/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using RunGroopWebApp.Data;
using RunGroopWebApp.Models;
using RunGroopWebApp.Models.ViewModels;

namespace RunGroopWebApp.Controllers
{
    public class PersonController : Controller
    {
        private readonly AppDbContext _context;

        public PersonController(AppDbContext context)
        {
            _context = context;
        }

        public ActionResult Index() 
        {
            var people = _context.People.Where(p => (p.IsDeleted == null || !p.IsDeleted.Value)).ToList();


            return View(people);
        }

        [HttpGet]
        public IActionResult CreateOrEdit(int? id = null)
        {
            if (id.HasValue)
            {
                var person = _context.People.FirstOrDefault(p => p.Id == id.Value);
                var personViewModel = new CreateOrEditPersonViewModel
                {
                    Name = person.Name,
                    BirthDate = person.BirthDate,
                    RG = person.RG,
                    Id = person.Id,
                };

                return PartialView("_CreateOrEdit", personViewModel);
            }

            return PartialView("_CreateOrEdit");
        }

        [HttpGet]
        public IActionResult PeopleList()
        {
            var people = _context.People.Where(p => (p.IsDeleted == null || !p.IsDeleted.Value)).ToList();

            return View(people);
        }

        [HttpGet]
        public IActionResult PeopleTableList()
        {
            var people = _context.People.Where(p => (p.IsDeleted == null || !p.IsDeleted.Value)).ToList();

            return View(people);
        }


        [HttpGet]
        public IActionResult Details(int id)
        {
            var person = _context.People.Where(p => (p.IsDeleted == null || !p.IsDeleted.Value) && p.Id == id).FirstOrDefault();

            return View(person);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(CreateOrEditPersonViewModel personViewModel)
        {
            try
            {
                // Instalar automapper depois para fazer correspondências entre dto e entidade e nao precisar mapear
                // Instalar lib validação

                // update
                if (personViewModel.Id != null && personViewModel.Id > 0)
                {
                    var person = _context.People.FirstOrDefault(p => p.Id == personViewModel.Id);

                    person.BirthDate = personViewModel.BirthDate;
                    person.RG = personViewModel.RG;
                    person.Name = personViewModel.Name;

                    _context.People.Update(person);
                    await _context.SaveChangesAsync();

                }
                else // create
                {
                    Person newPerson = new Person
                    {
                        BirthDate = personViewModel.BirthDate,
                        Name = personViewModel.Name,
                        RG = personViewModel.RG
                    };

                    _context.People.Add(newPerson);
                    await _context.SaveChangesAsync();
                }

                return Ok(Json(new DefaultJsonResponse
                {
                    Success = true,
                    Message = "Tudo certo :)"
                }));
            }
            catch(Exception e)
            {
                return BadRequest(Json(new DefaultJsonResponse
                {
                    Success = false,
                    Message = e.Message
                }));
            }
        }


        [HttpPost]
        public async Task<IActionResult> DeletePerson(int id)
        {
            try
            {
                var person = _context.People.FirstOrDefault(p => p.Id == id);

                person.IsDeleted = true;

                _context.People.Update(person);
                await _context.SaveChangesAsync();


                return Ok(Json(new DefaultJsonResponse
                {
                    Success = true,
                    Message = "Deletado com sucesso"
                }));
            }
            catch
            {
                return BadRequest(Json(new DefaultJsonResponse
                {
                    Success = false,
                    Message = "Deu algo errado"
                }));
            }
        }
    }
}

RunGroopWebApp/RunGroopWebApp/Controllers/RaceController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroopWebApp.Data;
using RunGroopWebApp.Models;

namespace RunGroopWebApp.Controllers
{
    public class RaceController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public RaceController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var races = _context.Races.Include(r => r.Address).ToList();
            return View(races);
        }


        public IActionResult Detail(int id)
        {
            var race = _context.Races.Include(r => r.Address).FirstOrDefault(r => r.Id == id);
            return View(race);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Race race)
        {
            if(!ModelState.IsValid)
            {
                return View(race);
            }


            var currentUserId = _userManager.GetUserId(User);
            race.AppUserId = currentUserId;


            _context.Races.Add(race);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

RunGroopWebApp/RunGroopWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RunGroopWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/DataTables/datatables.min.css"  />
    <link rel="stylesheet" href="~/RunGroopWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RunGroopWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">People</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Index">Clubs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Race" asp-action="Index">Races</a>
                        </li>


                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>

                            <li class="nav-item">
                                <form>
                                    <button asp-controller="Account" asp-action="Logout" class="btn btn-outline-danger">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Create/Edit Modal -->
    <div class="modal fade" id="createOrEditModal" tabindex="-1" aria-labelledby="createOrEditModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="createOrEditModalLabel"></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="modalContent"></div>
            </div>
        </div>
    </div>

    <!-- Details -->
    <div class="modal fade" id="detailsModal" tabindex="-1" aria-labelledby="detailsModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="detailsModalLabel"></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="modalContent"></div>
            </div>
        </div>
    </div>

    <partial name="~/Views/Partials/Application/_LoadingSpinner.cshtml"></partial>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RunGroopWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>



    <script src="~/lib/sweetalert2.all.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/plugins/inputmask/jquery.inputmask.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/plugins/jquery-validation-messages/messages_pt_BR.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/DataTables/datatables.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>